- name: Deploy .Net
  hosts: all
  become: yes

  vars:
    app_dir: "/var/www/crudwithauth"
    app_user: "www-data"
    db_name: "crud_db"
    db_user: "postgres"
    db_password: "postgres_password"
    redis_ports: [7000, 7001, 7002, 7003, 7004, 7005]

  tasks:
    - name: Check if .NET is already installed
      command: dotnet --version
      register: dotnet_check
      ignore_errors: yes
      changed_when: false

    - name: Install .NET 9 via Official Script (Reliable Method)
      shell: |
        curl -sSL https://dot.net/v1/dotnet-install.sh | bash /dev/stdin --channel 9.0 --install-dir /usr/share/dotnet
        ln -sf /usr/share/dotnet/dotnet /usr/bin/dotnet
      when: dotnet_check.failed
      args:
        creates: /usr/bin/dotnet

    - name: Install System Packages
      apt: 
        name: [postgresql, postgresql-contrib, redis-server, python3-psycopg2, acl, curl]
        state: present
        update_cache: yes
      register: apt_res
      until: apt_res is success
      retries: 5
      delay: 5

    - name: Configure PostgreSQL Database
      become_user: postgres
      block:
        - postgresql_db:
            name: "{{ db_name }}"
        - postgresql_user:
            name: "{{ db_user }}"
            password: "{{ db_password }}"
            db: "{{ db_name }}"  
            priv: "ALL"          

    - name: Ensure Redis directories exist
      file:
        path: "/var/lib/redis/{{ item }}"
        state: directory
        owner: redis
        group: redis
      loop: "{{ redis_ports }}"
      vars:
        port: "{{ item }}"

    - name: Configure Redis Nodes
      template:
        src: templates/redis.conf.j2
        dest: "/etc/redis/redis_{{ item }}.conf"
      loop: "{{ redis_ports }}"
      vars:
        port: "{{ item }}"
    
    - name: Start Redis instances
      shell: "redis-server /etc/redis/redis_{{ item }}.conf --daemonize yes"
      loop: "{{ redis_ports }}"
      vars:
        port: "{{ item }}"
      changed_when: false

    - name: Check Redis Cluster status
      shell: redis-cli -p 7000 cluster info
      register: redis_cluster_check
      ignore_errors: yes
      changed_when: false

    - name: Create Redis Cluster
      shell: >
        redis-cli --cluster create
        {% for p in redis_ports %} 127.0.0.1:{{ p }} {% endfor %}
        --cluster-replicas 1 --cluster-yes
      

    - name: Ensure app directory exists
      file: 
        path: "{{ app_dir }}"
        state: directory
        owner: "{{ app_user }}"
        mode: '0755'

    - name: Copy app artifacts to web folder
      copy:
        src: "./out/" 
        dest: "{{ app_dir }}/"
        owner: "{{ app_user }}"
        mode: '0644'
    
    - name: Render appsettings.json
      template: 
        src: templates/appsettings