name: CI-CD

on: 
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Ansible
        run: |
          sudo apt-get update
          sudo apt-get install -y ansible

      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: app-release
          path: ./out 

      - name: Run Ansible
        run: |
          # Просто запускаем плейбук без передачи переменных
          ansible-playbook -i "localhost," -c local deploy.yml
